travis:
  secure:
    BINSTAR_TOKEN: llvmKv7aAYE7ar5Sy0QqELgGssS1Fk0E4Y4bLEWQjETNwSIq/cVhQW/kFW9STQCubf+zLU3qcUhXnnd7wPR5zCpdPcEDwWtfDpTapf7v0Do5Ch0hNYnXsoPn9daw97ONemt9UshbCsDoeacg1lFlLDVrW+w53A8UcrXgCV49oEw8anvpcVlVf8Fb3v7OwxkCRn3w23CfJgD6xqTFyY9lTv4hNOLMfDvarra+LhI/M/m5M+WrWWo0abTy+8XTaOno/WqEdp6YhXRiUkAmSKk0qMDSgG8f02uhrU3ASTj6SXKSIjQPfhl0Y7N0L9d7hgnby5BvfqQGYVUXluBHRMQCLnAdyZabSBijMwqX2uYD1kY5u7TGAaomVwapiWxuFDiubRK8yZEfEqE5UgYgKkks3fzTCkdO38mffPKDW81tO3XYeVuFFhDFZXzQsjRnhZpLn+gagpYXc+SXRwRdAMVSE56EYJ2NJfP+Gz710tQmd8AqihZCSz8X801b9NRXco3R1tvTHd6H9/0U3f+UteEdTMntAo35TLED96mSKr9L5EejPrx6OibL90x/es8bYbpD1belJxtqv3eRRwB/fAGx7Ktk0l3WC4/5vxaxOGL1a4f3J0QoyrbAjxUBYlFdtBW9DrZOd+0agogbVWqUSMKOwq//EXIIuBpFkLpleFLZqv8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
